services:
  mesa:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_TURNSTILE_SITE_KEY=${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    container_name: mesa_app
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.mesa-sse.headers.customResponseHeaders.X-Accel-Buffering=no"
      - "traefik.http.middlewares.mesa-sse.headers.customResponseHeaders.Cache-Control=no-cache,no-transform"
      - "traefik.http.middlewares.mesa-sse.headers.customResponseHeaders.Connection=keep-alive"
      - "traefik.http.routers.mesa.middlewares=mesa-sse"
    networks:
      - red_infraestructura

networks:
  red_infraestructura:
    external: true